
# -*- coding: utf-8 -*-
#
# This file is part of Autobot.
# Copyright (C) 2015-2019 CERN.
#
# Autobot is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

language: python

sudo: required

dist: xenial

python: 3.7

cache:
  - pip

matrix:
  fast_finish: true
  allow_failures:
    - env: REQUIREMENTS=devel

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
  - REQUIREMENTS=devel

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder black"
  - "requirements-builder -e all --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e all --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e all --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

script: ./run-tests.sh


after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: inveniosoftware
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: inveniosoftware/autobot
    python: 3.6
